version: '3'
services: 
 php:
  image: php:7.2-apache
  volumes:
  - ./:/var/www/html
  - ./laravel:/var/www/html/laravel
  ports:
  - '8001:80'
  depends_on:
  - db

 db:
  image: mysql:5.7
  platform: linux/x86_64
  volumes:
  - ./:/var/lib/mysql
  ports:
  - '3002:3008'
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: larabel_db
    MYSQL_USER: user
    MYSQL_PASSWORD: password
